language: node_js
node_js:
  - "10.9"
before_install:
  - echo "registry=https://pkgs.dev.azure.com/mseng/_packaging/ApplicationInsights-Team/npm/registry/" > .npmrc
  - echo "" >> .npmrc
before_script:
  - cp .npmrc AISKU/
  - npm run build-prefixes
  - npm install grunt-cli -g