language: node_js
node_js:
  - "10.9"
before_install:
  - npm i -g npm@4.5.0
  - npm i -g grunt-cli
jobs:
  include:
    - script: ./.travis/test_rush.sh
      name: "Tests"
    - script: ./.travis/test_legacy.sh
      name: "Legacy Tests"
    - script: ./.travis/test_react_native.sh
      name: "React Native Tests"
