language: node_js
node_js:
  - "10.9"
before_install:
  - echo "//pkgs.dev.azure.com/mseng/_packaging/ApplicationInsights-Team/npm/registry/:_authToken=\${REGISTRY}" >> .npmrc
  - echo "" >> .npmrc
  - echo "//pkgs.dev.azure.com/mseng/_packaging/ApplicationInsights-Team/npm/:_authToken=\${NPM}" >> .npmrc
before_script:
  - cp .npmrc ApplicationInsights/
  - cp .npmrc AppInsightsCommon/
  - cp .npmrc AISKU/
  - cp .npmrc extensions/applicationinsights-properties-js/
  - cp .npmrc ApplicationInsights/applicationinsights-dependencies-js/
  - npm run build-prefixes
  - npm install grunt-cli -g